[project]
name = "graph-curvature"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numpy>=2.2.4",
    "plotly>=6.0.1",
    "pygraphviz>=1.14",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]
